version: '3'

services:
  gdbserver:
    image: camerondurham/xv6-docker
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    security_opt:
      - seccomp:unconfined
    privileged: true
    container_name: cs350_docker
    ports:
      - "7776:22"
      - "7777:7777"
      - "25000:25000"
    volumes:
        - ./data:/xv6_docker/
    working_dir: /xv6_docker/
    hostname: xv6_host

